#!/usr/bin/env python3
"""
Turn songs.json into a compact JS file the game loads from disk, plus rewrite
the per-song markdown files.

Each song carries two link sets:
  o = the original tune (what the terrace chant borrowed), per the wiki caption
  y = every recording on the page, originals included

The game defaults to `o`, which makes for a better round: you hear the tune
the chant is built on rather than a noisy crowd recording.

    python3 build-game-data.py
"""
import json
import pathlib
import re

src = json.load(open("songs.json", encoding="utf-8"))

songs, per_song = [], []
for r in src["songs"]:
    all_ids = [l["id"] for l in r["links"]]
    orig_ids = [l["id"] for l in r["links"] if l["original"]]
    per_song.append(r)
    if not all_ids:
        continue
    songs.append(
        {
            "n": r["song"],
            "c": r["category"].replace("קטגוריה:", ""),
            "w": r["wiki_url"],
            "a": r["original_artist"],
            "o": orig_ids,
            "y": all_ids,
        }
    )

songs.sort(key=lambda s: s["n"])

pathlib.Path("game").mkdir(exist_ok=True)
with open("game/songs-data.js", "w", encoding="utf-8") as f:
    f.write("/* GENERATED by build-game-data.py — do not edit by hand. */\n")
    f.write("window.HAPOEL_SONGS = ")
    json.dump(songs, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")

# ---- per-song files -----------------------------------------------------
out = pathlib.Path("songs")
out.mkdir(exist_ok=True)
for old in out.glob("*.md"):
    old.unlink()


def safe(name):
    n = re.sub(r'[\\/:*?"<>|\n\r\t]', "-", name).strip().strip(".")
    return n[:120] or "untitled"


seen = {}
for r in per_song:
    base = safe(r["song"])
    seen[base] = seen.get(base, 0) + 1
    fn = base if seen[base] == 1 else f"{base} ({seen[base]})"

    L = [f"# {r['song']}", "", f"- **קטגוריה:** {r['category']}", f"- **דף ויקיפועל:** {r['wiki_url']}"]
    if r["original_artist"]:
        L.append(f"- **המקור:** {r['original_artist']}")
    L.append("")

    orig = [l for l in r["links"] if l["original"]]
    rest = [l for l in r["links"] if not l["original"]]

    L.append("## 🎵 השיר המקורי")
    L.append("")
    if orig:
        L += [f"- [{l['label'] or 'ללא כותרת'}]({l['url']})" for l in orig]
    else:
        L.append("_בדף לא מסומן שיר מקורי._")
    L.append("")

    if rest:
        L += ["## ביצועים נוספים", ""]
        L += [f"- [{l['label'] or 'ללא כותרת'}]({l['url']})" for l in rest]
        L.append("")

    (out / f"{fn}.md").write_text("\n".join(L), encoding="utf-8")

playable_o = sum(1 for s in songs if s["o"])
print(f"game data: {len(songs)} songs")
print(f"  with an original tune: {playable_o}")
print(f"  original videos: {sum(len(s['o']) for s in songs)}")
print(f"  all videos: {sum(len(s['y']) for s in songs)}")
print(f"per-song files rewritten: {len(per_song)}")
