#!/usr/bin/env python3
"""
Dump hapoel.db to game/songs-data.js.

The database is the source of truth once you start editing, but the game also
ships a static songs-data.js for when it is served without server.py. Without
this step that fallback silently drifts — it would still list songs you have
since deleted.

    python3 export-static.py
"""
import collections
import json
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))

c = sqlite3.connect(f"file:{HERE}/hapoel.db?mode=ro", uri=True)
c.row_factory = sqlite3.Row
links = collections.defaultdict(list)
for r in c.execute("SELECT * FROM links ORDER BY song_id, pos, id"):
    links[r["song_id"]].append(dict(r))

songs = []
for r in c.execute("SELECT * FROM songs ORDER BY name"):
    ls = links[r["id"]]
    if not ls:
        continue
    songs.append({
        "n": r["name"],
        "c": (r["category"] or "").replace("קטגוריה:", ""),
        "w": r["wiki_url"] or "",
        "a": r["artist"],
        "o": [l["video_id"] for l in ls if l["original"]],
        "y": [l["video_id"] for l in ls],
    })
c.close()

out = os.path.join(HERE, "game", "songs-data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* GENERATED by export-static.py from hapoel.db — do not edit by hand. */\n")
    f.write("window.HAPOEL_SONGS = ")
    json.dump(songs, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")

print(f"{len(songs)} songs -> game/songs-data.js")
print(f"  with an original: {sum(1 for s in songs if s['o'])}")
print(f"  total videos    : {sum(len(s['y']) for s in songs)}")
